version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: PCL_MS
      POSTGRES_USER: PCL
      POSTGRES_PASSWORD: 123
    volumes:
      - D:\Love Babbar DSA\web dev\pclmanager\pclmanager\backend\docker-data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
